site_name: Docs Test

theme:
  name: material
  custom_dir: overrides  
  palette:
    primary: indigo

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - footnotes
