site_name: Docs Test

theme:
  name: material
  palette:
    primary: indigo

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
edit_uri: https://github.com/gubareve/sample-docs/edit/main/docs/
